### ISSUE TITLE
uv's & topology

### ISSUE THREAD

**Issue by circuitb** [torinos-yt/VVVVAlembic#1]
hello,
great stuff here !! 
just trying to apply a simple texture to a box 
but there's an issue with uv's 
see attached
![uvCompare](https://user-images.githubusercontent.com/1019218/79463547-46d26800-7ff9-11ea-8c02-a80e23b08a87.png)
![topoCompare](https://user-images.githubusercontent.com/1019218/79463550-476afe80-7ff9-11ea-809b-ed0c060eec9d.png)

**Comment by torinos-yt** [comment]
Hi.
Thanks for your issue, circuitb!

I fixed the UV problem that I can reproduce myself.
69404fd

topology problem, it is most likely due to the inherent coordinate system.
In most environments, the abc exporter seems to convert to +Yup & right-hand coordinate system.
This plugin converts the right-hand coordinate system to the left-hand coordinate system.

Is it possible to tell me your export environment and upload the original scene?

**Comment by circuitb** [comment]
hi thanks for the fix,
here's what i found
single geometries exported straight from C4D or houdini
have proper uv's with the AlembicFile (DX11.Geometry Alembic) 
using the AlembicScene > Mesh (DX11.Geometry Alembic) only proper alembic mesh  formated
in houdini  are working with attribtransferbyuv1 (pos, norm, uv)  before the rop alembic export

ps: found another bug when switching twice from  AlembicFile (DX11.Geometry Alembic) to Mesh (DX11.Geometry Alembic) it crash vvvv (berta39, dx11 v1.3.1.1)
[compareABC.zip](https://github.com/torinos-yt/VVVVAlembic/files/4504239/compareABC.zip)

**Comment by torinos-yt** [comment]
Thanks for sharing your environment.

This is more fixes for UV problem. The release has also been updated.
3a713c1

As for the new bug, the direct cause has yet to be determined.

However, the AlembicFile node is the legacy code (it only reads scenes of simple structures and doesn't transform coordinate systems) that I plan to remove, and using the AlembicScene node doesn't seem to cause this problem.

For now, i recommend using AlembicScene node.

**Comment by circuitb** [comment]
hello again,
everything works as intended with the latest release
thanks
